/*
File:         main.c
Purpose:      Calls the run_analysis function in tide_analyzer
Author:			  Your names
Student #s:		12345678 and 12345678
CS Accounts:	a1a1 and b2b2
Date:				  Add the date here
*/

/******************************************************************
DO NOT EDIT THIS FILE
******************************************************************/

/* Preprocessor directives */
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include "tide_analyzer.h"
#include "discrete_fourier_transform.h"

#define _CRT_SECURE_NO_WARNINGS
/*
  The preprocessor directive above allows the use of the fopen and sscanf
  in Visual Studio, rather than requiring fopen_s and sscanf_s.
  You may use fopen_s and sscanf_s while developing and debugging in Visual Studio,
  but please ensure that you replace these with fopen and sscanf prior to
  submitting your code to PrairieLearn.
*/

#define NUMBER_OF_READINGS  131072 /* This = 2^17 (hint!) */
#define NOISE_FILTER        0.01   /* Used to eliminate noise from observation */
#define EXPONENT            17     /* Can be used for call to fft */
#define LINESIZE            128    /* Maximum line length in data file */
#define SAMPLING_FREQUENCY  48     /* Number of tidal readings taken day */
#define MIN_VALUES_PER_LINE 2      /* Min # of integers on each line of data file */
#define MAX_VALUES_PER_LINE 6      /* Max # of integers on each line of data file */
#define FFT_ALGOR_BUFFER    4      /* Prevents Run Time Check Failure #2
If you experience this error upon
closing your program, increase the size
of the readings array to
NUMBER_OF_READINGS + FFT_ALGOR_BUFFER */
#define FILE_NAME           "puddlejump.txt"
#define RESULT_FILE_NAME    "result.txt"
/*
Main function drives the program.
PRE:       NULL (no pre-conditions)
POST:      NULL (no side-effects)
RETURN:    IF the program exits correctly THEN 0 ELSE 1
*/
int main(void)
{
    run_analysis();
/*
    FILE* file_pointer = NULL;
    fopen_s(&file_pointer,FILE_NAME, "r");
    double readings[NUMBER_OF_READINGS];

   int num1, num2, num3,num4,num5,num6;
    int values = 0;
    values = sscanf_s(str, "%d %d %d %d %d %d %d", &num1, &num2, &num3, &num4,&num5,&num6);
    printf("%d\n",values);
    printf("%d\n", num6);
    system("pause"); 
    
    process_file(readings,file_pointer);
   */
    return 0;
}